### ISSUE TITLE
TabView无法保持状态 & 编译报错：字段缺失

### ISSUE THREAD

**Issue by AllinProgram** [debuggerx01/flutter_ecommerce_demo#1]
站友你好，感谢开源这么好的一个学习项目。在这个项目中我发现两个问题，还希望帮忙解惑第一个问题：

1. 编译报错：provider定义相关字段缺失：collectionProvider、cartProvider、userIdProvider等；
2. 部署后运行发现Tab页之间未持久状态，会丢失页面状态。

**Comment by debuggerx01** [comment]
1. riverpod为了减少模板代码的编写量，使用了注解+代码生成的模式，所以编译前需要手动执行 `dart run build_runner build`: [https://riverpod.dev/zh-Hans/docs/concepts/about_code_generation](关于代码生成)

2. 这只是一个面试的题目，并没有详细的需求和设计，总共也只花了一天多完成，自然不会考虑到所有问题。如果需要保持TabView的状态，一种方法是重构为IndexedStack，更推荐的方法是将ItemList组件更改为继承ConsumerStatefulWidget，然后混入AutomaticKeepAliveClientMixin来实现。

**Comment by AllinProgram** [comment]
十分感谢解惑
